version: '3.8'

services:
  backend:
    build:
      context: ./server
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - frontend

  frontend:
    build:
      context: ./client
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/src/app
